name: Runtime-Python
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/runtime-python.yml'
      - 'docker/images/python/**'
      - 'daemon/**'

jobs:
  build:
    name: Build Docker image
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & Publish to Docker Registry
        uses: wuhan005/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.hub.docker.com
          repository: registry.hub.docker.com/elainaruntime/python
          tag_format: "%YYYY%_%MM%_%DD%_%H%%m%%s%"
          file: ./docker/images/python/Dockerfile
          auto_tag: true
